language: python
sudo: required  # for python 3.7, may not be needed in future
dist: xenial  # for python 3.7
python:
  - "3.9"
node_js:
  - "12"
install:
 - pip install -r test_requirements.txt
 - npm install

script: tox && coverage xml && codecov
